"""empty message

Revision ID: 4fc8e344db1e
Revises: 
Create Date: 2020-06-24 13:26:05.133216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc8e344db1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diretorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('diretor', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diretor'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('trainees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('association',
    sa.Column('trainee_id', sa.Integer(), nullable=False),
    sa.Column('diretoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diretoria_id'], ['diretorias.id'], ),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ),
    sa.PrimaryKeyConstraint('trainee_id', 'diretoria_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_table('trainees')
    op.drop_table('diretorias')
    # ### end Alembic commands ###
