"""empty message

Revision ID: f76d91bb591a
Revises: 4fc8e344db1e
Create Date: 2020-06-29 14:14:13.301397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f76d91bb591a'
down_revision = '4fc8e344db1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diretorias', sa.Column('descricao', sa.String(), nullable=True))
    op.add_column('diretorias', sa.Column('ref_imagem', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diretorias', 'ref_imagem')
    op.drop_column('diretorias', 'descricao')
    # ### end Alembic commands ###
